language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - cmake
    - libxml2
    - libxml2-dev
    - libxml++2.6-dev
    - libxslt1-dev
install:
  - mkdir $HOME/usr
  - curl -L -O http://xrootd.org/download/v4.3.0/xrootd-4.3.0.tar.gz
  - tar xzf xrootd-4.3.0.tar.gz
  - mkdir xrootd-build && cd xrootd-build
  - cmake ../xrootd-4.3.0 -DCMAKE_INSTALL_PREFIX=$HOME/usr -DENABLE_PERL=FALSE
  - make
  - make install
  - cd -
# command to run tests
script:
  - python foo.py
