language: python
python:
  - "2.7"
  - "3.5"
install:
  - mkdir $HOME/usr
  - curl -L -O http://xrootd.org/download/v4.3.0/xrootd-4.3.0.tar.gz
  - tar xzf xrootd-4.3.0.tar.gz
  - mkdir xrootd-build && cd xrootd-build
  - export CXXFLAGS=-isystem\ /usr/include/libxml2
  - cmake ../xrootd-4.3.0 -DCMAKE_INSTALL_PREFIX=$HOME/usr -DENABLE_PERL=FALSE
  - make
  - make install
  - cd -
before_script:
  - export PATH=$HOME/usr/bin:$PATH
  - export LD_LIBRARY_PATH=$HOME/usr/lib:$LD_LIBRARY_PATH
  - python foo.py
# command to run tests
script:
  - python test_open_eos.py
